export interface Property{
    propertyId: 0,
    propertyName?: string,
    propertyType?: string,
    price?: 0,
    facility?: 0,
    address?: string,
    facing?: string,
    amenities?: string,
    noOfCarParkings?: 0,
    pictures?: string,
    furnishedStatus?: string,
    askingPrice?: 0,
    finalPrice?: 0,
    noOfBeds?: 0,
    noOfBathRooms?: 0,
    noOfBalcony?: 0,
    dimention?: 0,
    flatFloor?: 0,
    totalFloors?: 0,
    noOfFlatsInAFloor?: 0,
    propertyAge?: 0,
    noOfLifts?: 0
  }